# Generated by Django 4.2.6 on 2023-11-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        verbose_name="Порядковый номер изображения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название изображения"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="places.place",
                    ),
                ),
            ],
        ),
    ]
