# Generated by Django 4.2.6 on 2023-11-05 22:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_placeimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["pk"],
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.RemoveField(model_name="placeimage", name="title",),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
